#format = "(bold green)$directory$git_branch$character"

format = """
$directory\
$git_branch\
$git_metrics\
$nodejs\
$python\
$rust\
$c\
$sudo\
ğŸ—¿ $character 
"""

add_newline = false

[nodejs]
format = "[$symbol]($style)"

[directory]
style = "bold cyan"
truncation_length = 10
truncate_to_repo = false

[git_branch]
symbol = "î‚  "
format = "on [$symbol$branch]($style) "

[git_metrics]
disabled = false

[rust]
symbol = "ğŸ¦€"
format = "[$symbol]($style)"

[python]
symbol = "ğŸ"
format = '[$symbol]($style)'

[c]
format = '[$symbol]($style)'

[sudo]
format = '[$symbol]($style)'
disabled = false
